apiVersion: v1
kind: Service
metadata:
  name: consumer-api
  labels:
    tier: consumer
spec:
  ports:
  - port: 8000
  selector:
    tier: consumer
  type: LoadBalancer

# kubectl port-forward svc/consumer-api 8000:8000
# minikube service --url consumer-api
