apiVersion: v1
kind: Service
metadata:
  name: consumer-spa
  labels:
    tier: consumer
spec:
  ports:
  - port: 4200
    targetPort: 80
  selector:
    tier: consumer
  type: NodePort

# kubectl port-forward svc/consumer-spa 4200:80
# minikube service --url consumer-spa
