apiVersion: v1
kind: Service
metadata:
  name: producer-api
  labels:
    tier: producer
spec:
  ports:
  - port: 5000
    targetPort: 80
  selector:
    tier: producer
  type: NodePort

# kubectl port-forward svc/producer-api 5000:80
# minikube service --url producer-api
